//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPSEditerFinal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDPSEditerFinal.Properties.ResourceSetting", typeof(ResourceSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称	物品代码	分类	AP	DP	HIT	EV	Range	是否能在游戏中获得	价格	特效
        ///岩石	00	其他	45	0	95	0	1	可	80	
        ///铁剑	01	剑类	20	0	95	0	1	不可	200	
        ///长剑	02	剑类	30	0	100	0	1	可	300	 
        ///白刃剑	03	剑类	50	0	95	0	1	可	500	
        ///巨剑	04	剑类	70	0	100	0	1	可	850	
        ///宽刃剑	05	剑类	85	0	110	0	1	可	900	
        ///护手剑	06	剑类	110	10	115	0	1	可	1300	附加10%防御力
        ///锯齿剑	07	剑类	135	0	120	0	1	可	1350	
        ///邪神剑	08	剑类	165	0	125	0	1	可	2200	
        ///雷神之剑	09	剑类	180	0	130	0	1	可	3200	130点雷电伤害(距离2,范围1)
        ///寒冰剑	0A	剑类	230	0	130	0	1	不可	5000	
        ///圣火之剑	0B	剑类	280	0	130	0	1	不可	7500	
        ///大地之剑	0C	剑类	300	0	95	0	1	不可	20000	
        ///天空之剑	0D	剑类	280	0	95	0	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码	职业
        ///0	剑士
        ///1	剑圣
        ///2	剑帝
        ///3	英雄
        ///4	战士
        ///5	圣战士
        ///6	狂战士
        ///7	骑士
        ///8	圣骑士
        ///9	大地骑士
        ///	
        ///0A	弓兵
        ///0B	神箭手
        ///0C	狙击手
        ///0D	魔导师
        ///0E	法师
        ///0F	巫师
        ///10	僧侣
        ///11	大僧侣
        ///12	大祭司
        ///13	武道家
        ///	
        ///14	武圣
        ///15	武神
        ///16	技师
        ///17	机械伯爵
        ///18	机械大师
        ///19	机兵
        ///1A	魔神
        ///1B	魔导王
        ///1C	魔导战士
        ///1D	武士
        ///	
        ///1E	重装武士
        ///1F	飞兵
        ///20	妖魔
        ///21	守护兽
        ///22	将军
        ///23	佣兵
        ///24	要塞炮
        ///25	恶灵
        ///26	活尸
        ///.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 栏位,编号,魔法,魔法值
        ///1,1,暴雷绝击,32
        ///1,2,奔雷弹,15
        ///1,3,落雷术,8
        ///1,4,圣光柱,40
        ///1,5,光之箭,20
        ///1,6,烈狱之火,35
        ///1,7,狂暴巨焰,15
        ///1,8,业火,7
        ///2,1,治愈之风,10
        ///2,2,恢复之光,4
        ///2,3,鬼动死灵阵,100
        ///2,4,震空重力弹,35
        ///2,5,封神裂震,95
        ///2,6,裂地术,45
        ///2,7,绝杀冰封,20
        ///2,8,冰暴术,10
        ///3,1,咒杀术,100
        ///3,2,神行术,40
        ///3,3,传送术,50
        ///3,4,神之祝福,50
        ///3,5,麻痹术,20
        ///3,6,腐毒术,10
        ///3,7,封魔咒术,25
        ///3,8,痊愈之泉,25
        ///4,1,灵弹超必杀,35
        ///4,2,流星箭,40
        ///4,3,轰神炮,75
        ///4,4,狱炎烈破弹,65
        ///4,5,金刚斩,30
        ///4,6,强力冲击,50
        ///4,7,魔龙霸炎,65
        ///4,8,甦愈术,30
        ///5,1,万神降临,130
        ///5,2,极度冰冻,65
        ///5,3,冰魔超速弹,35
        ///5,4,暴炎狂龙,60
        ///5,5,圣龙烈霸斩,100
        ///5,6,超重力黑洞,80
        ///5,7,镇魂之歌,55
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人 物	系 别	系 别	魔 法
        ///兰迪斯	一般	剑　士	&quot;业火,狂暴巨焰,烈狱之火&quot;
        ///	光明	剑　圣	暴炎狂龙
        ///	黑暗	剑　帝	&quot;暴炎狂龙,魔龙霸焰斩&quot;
        ///	特殊	英　雄	&quot;业火,狂暴巨焰,烈狱之火,暴焰狂龙,传送术,痊愈之泉,魔龙霸焰斩,圣龙霸烈斩&quot;
        ///尤利安	僧　侣	僧　侣	&quot;恢复之光,治愈之风,痊愈之泉,封魔咒术&quot;
        ///	光明	大僧侣	&quot;镇魂之歌,苏愈术&quot;
        ///	黑暗	大祭司	&quot;光之箭,圣光柱,神之祝福,苏愈术,镇魂之歌&quot;
        ///亚克	一般	骑　士	
        ///	光明	圣骑士	痊愈之泉
        ///	黑暗	大地骑士	强力冲击
        ///法莲娜	一般	魔导士	&quot;落雷术,奔雷弹,暴雷绝击,恢复之光&quot;
        ///	光明	法　师	&quot;审判之雷,光之箭,圣光柱,痹术,治愈之风,痊愈之泉&quot;
        ///	黑暗	巫　师	&quot;审判之雷,震空重力弹,超重力黑洞,治愈之风,万神降临,麻痹术&quot;
        ///裘娜	一般	战　士	
        ///	光明	圣战士	金刚斩
        ///	黑暗	狂战士	金刚斩
        ///费塔加	一般	魔导士	&quot;冰暴术,绝杀冰封,冰魔超速弹,裂地术&quot;
        ///	光明	法　师	&quot;极度冰冻,光之箭,圣光柱,治愈之风,痊愈之泉&quot;
        ///	黑暗	巫　师	&quot;封神裂震,极度冰冻&quot;
        ///布兰多	一般	技　师	
        ///	光明 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MagicAndJob {
            get {
                return ResourceManager.GetString("MagicAndJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码	名字
        ///0	人类
        ///1	妖鬼
        ///2	魔族
        ///3	机械
        ///4	兽人
        ///5	龙族
        ///6	其他
        ///.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码	姓名	职业
        ///00	蓝迪斯	剑士
        ///01	法莲娜	魔导士
        ///02	费塔加	魔导士
        ///03	裘娜	战士
        ///04	亚克	骑士
        ///05	玛丽安	弓兵
        ///06	尤利安	僧侣
        ///07	琴琴	武者
        ///08	布蓝多	技师
        ///09	盖亚	机兵
        ///0A	珊	法师
        ///0B	蓝斯洛特	圣骑士
        ///0C	索尔	英雄
        ///0D	卡里斯	武圣
        ///0E	亚雷斯	圣骑士
        ///0F	蓝迪斯	剑圣
        ///10	法莲娜	法师
        ///11	费塔加	法师
        ///12	裘娜	圣战士
        ///13	亚克	圣骑士
        ///14	玛丽安	神箭手
        ///15	尤利安	大僧侣
        ///16	琴琴	武圣
        ///17	布蓝多	机械伯爵
        ///18	蓝迪斯	剑帝
        ///19	法莲娜	巫师
        ///1A	费塔加	巫师
        ///1B	裘娜	狂战士
        ///1C	亚克	大地骑兵
        ///1D	玛丽安	阻击王
        ///1E	尤利安	大祭司
        ///1F	琴琴	武神
        ///20	布蓝多	机械大师
        ///21	蓝迪斯	英雄
        ///4F	野武士	武士
        ///52	狼人	妖魔
        ///4A	蛇魔女	妖魔
        ///65	冰魔导师	魔导师
        ///66	魔导士	魔导士
        ///.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
    }
}
